@startuml

title __DEMO's Class Diagram__\n

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.Benchmark {
        + elementCount : int
        ~ cars : List<Car>
        ~ ids : List<String>
        + generateIdsAndCars()
        {static} + main()
        + putMap()
        {static} + putMappings()
        + removeCarMap()
        {static} ~ generateCars()
        {static} ~ generateIds()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.Benchmark.FullMap {
        ~ cars : List<Car>
        ~ carsMap : HashMap<String, Car>
        ~ ids : List<String>
        + fillCarMap()
        + generateIdsAndCars()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.Car {
        {static} - currentYear : int
        - make : String
        {static} - maxPrice : double
        - mileage : int
        {static} - minPrice : double
        {static} - minYear : int
        - model : String
        - price : double
        - year : int
        + Car()
        + Car()
        + Car()
        + Car()
        + equals()
        + getMake()
        + getMileage()
        + getModel()
        + getPrice()
        + getYear()
        + hashCode()
        + parse()
        + setMileage()
        + setPrice()
        + toString()
        - validate()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.Car.Builder {
        {static} - MODELS : String[][]
        {static} - RANDOM : Random
        - make : String
        - mileage : int
        - model : String
        - price : double
        - year : int
        + build()
        + buildRandom()
        + make()
        + mileage()
        + model()
        + price()
        + year()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.CarsGenerator {
        {static} - ID_CODE : String
        - cars : Queue<Car>
        - keys : Queue<String>
        {static} - serNr : int
        {static} + generateId()
        {static} + generateShuffleCars()
        {static} + generateShuffleIds()
        + generateShuffleIdsAndCars()
        + getCar()
        + getCarId()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.DemoExecution {
        {static} + main()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.ManualTest {
        {static} + executeTest()
        {static} + main()
        {static} - executeCarMapOaTests()
        {static} - executeCarMapTests()
    }
  }
  

  edu.ktu.ds.lab3.demo.Benchmark +-down- edu.ktu.ds.lab3.demo.Benchmark.FullMap
  edu.ktu.ds.lab3.demo.Car .up.|> edu.ktu.ds.lab3.utils.Parsable
  edu.ktu.ds.lab3.demo.Car +-down- edu.ktu.ds.lab3.demo.Car.Builder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
